version: 2
updates:
- package-ecosystem: cargo
  directory: /kernel
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: /runner
  schedule:
    interval: daily
  open-pull-requests-limit: 10

