[package]
name = "tkern"
version = "0.1.0"
edition = "2018"
authors = ["Victor Koenders <victor.koenders@gmail.com>"]

[dependencies]
volatile = "0.4"
spin = "0.9"
multiboot2 = "0.11"
bitflags = "1.3"
x86_64 = "0.14"
cortex-a = "6.0"
pic8259 = "0.10.1"
pc-keyboard = "0.5"
pin-project-lite = "0.2"
cooked-waker = "5.0"

[dependencies.futures]
version = "0.3"
default_features = false

[dependencies.smallvec]
version = "1.4"
features = ["union", "const_generics", "specialization"]

[dependencies.crossbeam]
version = "0.8"
default_features = false
# features = ["alloc"]

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
