[package]
name = "tkern"
version = "0.1.0"
edition = "2018"
authors = ["Victor Koenders <victor.koenders@gmail.com>"]

[dependencies]
volatile = "0.3"
spin = "0.7"
multiboot2 = "0.10"
bitflags = "1.2"
x86_64 = "0.13"
# cortex-a = "5.1"
pic8259_simple = "0.2"
pc-keyboard = "0.5"

[dependencies.smallvec]
version = "1.4"
features = ["union", "const_generics", "specialization"]

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
