[package]
name = "tkern"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cortex-a = "7.2.0"
tock-registers = "0.7.0"
utils = { path = "libs/utils" }

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
