[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "boot",
]

[dependencies]
bootloader = "0.10"
conquer-once = { version = "0.3.2", default-features = false }
log = { version = "0.4.14", default-features = false }
spinning_top = "0.2.4"
x86_64 = "0.14.4"

[dependencies.font8x8]
version = "0.3.1"
default-features = false
features = ["unicode"]
