[package]
name = "tkern"
version = "0.1.0"
edition = "2018"
authors = ["Victor Koenders <victor.koenders@gmail.com>"]

[dependencies]
volatile = "0.3"
spin = "0.5"
multiboot2 = "0.9"
bitflags = "1.2"
x86_64 = "0.11"
cortex-a = "3.0"

[dependencies.lazy_static]
version = "1.4"
features = ["spin_no_std"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
