[workspace]
members = [
	"driver/interface",

	"driver/bcm2837",
	"driver/bcm2837/pac",

	"sys/aarch64",
]
exclude = [
	"test"
]

[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = "1.0.0"
driver = { path = "driver/interface" }

[target."cfg(target_arch = \"aarch64\")".dependencies]
sys-aarch64 = { path = "sys/aarch64" }

