[package]
name = "bcm2837_pac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcell = "0.1.3"

[build-dependencies]
svd2rust = "0.21"
