on: [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Setup rust toolchain
      run: rustup show
    
    - name: Cache cargo crates
      id: cache-cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/rust-objcopy
          ~/.cargo/bin/cargo-make
        key: ${{ runner.os }}-cargo-bin

    - name: Install cargo-binutils
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-binutils 

    - name: Install cargo-make
      if: steps.cache-cargo.outputs.cache-hit != 'true'
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-make

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: build
