on: [push, pull_request]

name: Rust

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Nightly
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: xbuild