on: [push, pull_request]

name: Rust

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rust-src,llvm-tools-preview
 
    - name: Install cargo-binutils
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-binutils

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: run
        args: -- build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt, clippy

    - name: Check formatting (Runner)
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run clippy (Runner)
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --workspace -- -D warnings

    - name: Check formatting (Kernel)
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --manifest-path=kernel/Cargo.toml -- --check
 
    - name: Add aarch64-unknown-none-softfloat
      run: rustup target add aarch64-unknown-none-softfloat

    - name: Run clippy (Kernel)
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --manifest-path=kernel/Cargo.toml --target aarch64-unknown-none-softfloat -- -D warnings
    
